log:
  level: debug
  #file: stderr
  file: /var/log/surftp/server.log
  audit: /var/log/surftp/access.log
server:
  port: 2222
  host_key: /etc/surftp/ssh_host_ed25519_key
users:
  home_base: /tmp/sftp-users
